spring:
  application:
    name: timmy-todo-app

  profiles:
    active: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100

  flyway:
    enabled: true
    baseline-on-migrate: true

  jackson:
    default-property-inclusion: non_null

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
