CREATE TABLE todo_entity
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(255) NOT NULL,
    body          VARCHAR(255),
    created_date  TIMESTAMP    NOT NULL,
    modified_date TIMESTAMP    NOT NULL,
    completed     BOOLEAN      NOT NULL
);